name: app_medicamentos
description: App Medicamentos UASLP
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_datepicker: ^23.1.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_apesaam.png
