name: app_medicamentos
description: App Medicamentos UASLP
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  syncfusion_flutter_datepicker: ^25.2.6
  flutter_localization: ^0.2.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  path_provider: ^2.1.1
  intl: ^0.19.0
  syncfusion_flutter_core: ^25.2.6
  syncfusion_localizations: ^25.2.6
  #dropdown_textfield: ^1.0.8
  provider: ^6.1.2
  url_launcher: ^6.2.1
  flutter_local_notifications: ^16.1.0
  mask_text_input_formatter: ^2.6.0
  page_transition: ^2.1.0
  flutter_alarm_clock: ^0.1.1
  flutter_holo_date_picker: ^1.1.3
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_apesaam.png
    - assets/images/icon_profile2.png
    - assets/images/icon_ok.png
    - assets/images/icon_error.png

  fonts:
    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Light.ttf
      - asset: assets/fonts/Roboto-Medium.ttf
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Thin.ttf

